openapi: 3.0.0
info:
  title: AMI
  description: fuck the cs hse
  contact: {}
  version: 0.0.1
servers:
  - url: 'https://bestdomainever.com/api'
    variables: {}
tags:
  - name: auth
    description: about authentication
  - name: students
    description: about students
  - name: groups
    description: about groups
  - name: deadlines
    description: ''
