openapi: 3.0.0
info:
  description: fuck the cs hse
  version: 1.0.0
  title: AMI
tags:
  - name: auth
    description: about authentication
  - name: students
    description: about students
  - name: groups
    description: about groups
servers:
  - url: 'https://bestdomainever.com/api'
