openapi: 3.0.0
info:
  title: AMI API FRONT
  description: "Описание API для фронта ами"
  contact: {}
  version: 1.0.1

servers:
  - url: 'https://new.ami161.ru/api'
    variables: {}

tags:
  - name: auth
    description: Аутенфикация пользователей
  
  - name: files
    description: Работа с файлами
  
  - name: students
    description: Работа со студентами
  
  - name: groups
    description: Работа с группами
  
  - name: deadlines
    description: ''
